WITH DD07T_SOURCE AS
(
SELECT
	DDTEXT,
	DOMVALUE_L,
	DOMNAME,
	DDLANGUAGE
FROM {{ ref('DLV_STAGING_DD07T') }}
),
Projection_1 AS
(
SELECT 
	MANDT,
	KUNNR,
	VKORG,
	VTWEG,
	SPART,
	ERNAM,
	ERDAT,
	LOEVM,
	VERSG,
	AUFSD,
	KALKS,
	BZIRK,
	KONDA,
	PLTYP,
	AWAHR,
	INCO1,
	INCO2,
	LIFSD,
	AUTLF,
	ANTLF,
	KZTLF,
	KZAZU,
	LPRIO,
	VSBED,
	FAKSD,
	MRNKZ,
	PERRL,
	WAERS,
	KTGRD,
	ZTERM,
	VWERK,
	KVGR1,
	KVGR2,
	KVGR3,
	KVGR4,
	KVGR5,
	BOKRE,
	BOIDT,
	KURST,
	PRFRE,
	KKBER,
	CASSD,
	RDOFF,
	UEBTO,
	UNTTO,
	UEBTK,
	PVKSM,
	PODKZ,
	PODTG,
	BLIND,
	"/BEV1/EMLGPFAND" AS _BEV1_EMLGPFAND,
	"/BEV1/EMLGFORTS" AS _BEV1_EMLGFORTS,
	FSH_KVGR6,
	FSH_KVGR7,
	FSH_KVGR8,
	FSH_KVGR9,
	FSH_KVGR10,
	FSH_GRREG,
	FSH_SC_CID,
	FSH_VAS_DETC,
	FSH_VAS_CG,
	FSH_GRSGY,
	FSH_SS,
	FSH_MSOCDC,
	FSH_MSOPID,
	ZZPAR_ID,
	FSH_RESGY,
	ZZGGN,
	ZZNGN,
	ZZSGN,
	ZZKVGR6,
	ZZKVGR7
FROM {{ ref('DLV_STAGING_KNVV') }}
),
Projection_2 AS
(
SELECT 
	DOMNAME,
	DDLANGUAGE,
	DOMVALUE_L,
	DDTEXT
FROM DD07T_SOURCE
WHERE DOMNAME = 'ZFSH_KVGR_6' AND
DDLANGUAGE = 'E'
),
Projection_3 AS
(
SELECT 
	DOMNAME,
	DDLANGUAGE,
	DOMVALUE_L,
	DDTEXT
FROM DD07T_SOURCE
WHERE DOMNAME = 'ZFSH_KVGR7' AND
DDLANGUAGE = 'E'
),
Join_1 AS
(
SELECT 
	Projection_1.MANDT AS Client,
	Projection_1.KUNNR AS CustomerNumber,
	Projection_1.VKORG AS SalesOrganization,
	Projection_1.VTWEG AS DistributionChannel,
	Projection_1.SPART AS Division,
	Projection_1.ERNAM AS NameofPersonWhoCreatedtheObject,
	Projection_1.ERDAT AS DateonWhichRecordWasCreated,
	Projection_1.LOEVM AS DeletionFlagForCustomerSalesLevel,
	Projection_1.VERSG AS CustomerStatisticsGroup,
	Projection_1.AUFSD AS CustomerOrderBlockSalesArea,
	Projection_1.KALKS AS PricingProcedureAssignedToThisCustomer,
	Projection_1.BZIRK AS SalesDistrict,
	Projection_1.KONDA AS PriceGroupCustomer,
	Projection_1.PLTYP AS PriceListType,
	Projection_1.AWAHR AS OrderProbabilityOfTheItem,
	Projection_1.INCO1 AS IncotermsPart1,
	Projection_1.INCO2 AS IncotermsPart2,
	Projection_1.LIFSD AS CustomerDeliveryBlockSalesArea,
	Projection_1.AUTLF AS CompletedDeliveryDefinedForEachSalesOrder,
	Projection_1.ANTLF AS MaximumNumberOfPartialDeliveriesAllowedPerItem,
	Projection_1.KZTLF AS PartialDeliveryAtItemLevel,
	Projection_1.KZAZU AS OrderCombinationIndicator,
	Projection_1.LPRIO AS DeliveryPriority,
	Projection_1.VSBED AS ShippingConditions,
	Projection_1.FAKSD AS Billingblockforcustomersalesanddistribution,
	Projection_1.MRNKZ AS ManualInvoiceMaintenance,
	Projection_1.PERRL AS InvoiceListSchedulecalendarIdentification,
	Projection_1.WAERS AS Currency,
	Projection_1.KTGRD AS AccountAssignmentGroupforCustomer,
	Projection_1.ZTERM AS TermsOfPaymentKey,
	Projection_1.VWERK AS DeliveringPlantOwnorExternal,
	Projection_1.KVGR1 AS CustomerGroup1,
	Projection_1.KVGR2 AS CustomerGroup2,
	Projection_1.KVGR3 AS CustomerGroup3,
	Projection_1.KVGR4 AS CustomerGroup4,
	Projection_1.KVGR5 AS CustomerGroup5,
	Projection_1.BOKRE AS IndicatorCustomerIsRebateRelevant,
	Projection_1.BOIDT AS Startofvalidityperfortherebateindexforthecustomer,
	Projection_1.KURST AS ExchangeRateType,
	Projection_1.PRFRE AS RelevantForPriceDeterminationID,
	Projection_1.KKBER AS CreditControlArea,
	Projection_1.CASSD AS SalesBlockForCustomerSalesArea,
	Projection_1.RDOFF AS SwitchOffRounding,
	Projection_1.UEBTO AS OverdeliveryToleranceLimit,
	Projection_1.UEBTK AS UnlimitedOverdeliveryAllowed,
	Projection_1.UNTTO AS UnderdeliveryToleranceLimit,
	Projection_1.PVKSM AS CustomerProcedureForProductProposal,
	Projection_1.PODKZ AS RelevantForPODProcessing,
	Projection_1.PODTG AS TimeframeforConfirmationofPOD,
	Projection_1.BLIND AS IndexStructureActiveforSubsequentSettlementinAB,
	Projection_1._BEV1_EMLGPFAND AS DepositOnEmpties,
	Projection_1._BEV1_EMLGFORTS AS IndicatorForEmptiesUpdate,
	Projection_1.FSH_KVGR6 AS CustomerGroup6,
	Projection_1.FSH_KVGR7 AS CustomerGroup7,
	Projection_1.FSH_KVGR8 AS CustomerGroup8,
	Projection_1.FSH_KVGR9 AS CustomerGroup9,
	Projection_1.FSH_KVGR10 AS CustomerGroup10,
	Projection_1.FSH_GRREG AS GroupingRule,
	Projection_1.FSH_RESGY AS ReleaseStrategy,
	Projection_1.FSH_SC_CID AS CustomerVendorID,
	Projection_1.FSH_VAS_DETC AS VASDeterminationMode,
	Projection_1.FSH_VAS_CG AS ValueAddedServicesCustomerGroup,
	Projection_1.FSH_GRSGY AS ARUNGroupingStrategy,
	Projection_1.FSH_SS AS OrderSchedulingStrategy,
	Projection_1.FSH_MSOCDC AS DistributionCenterofCustomer,
	Projection_1.FSH_MSOPID AS IdentificationoftheCustomerinthePartnerSystem,
	Projection_1.ZZPAR_ID AS CustomerNumbr,
	Projection_1.ZZGGN AS GlobalGroupingNumber,
	Projection_1.ZZNGN AS NationalGroupingNumber,
	Projection_1.ZZSGN AS SalesGroupingNumber,
	Projection_1.ZZKVGR6 AS HospitalDepartment,
	Projection_1.ZZKVGR7 AS CDCLevel, 
	Projection_2.DDTEXT AS HospitalDepartmentText
FROM 
Projection_1
LEFT OUTER JOIN 
Projection_2
ON Projection_1.ZZKVGR6 = Projection_2.DOMVALUE_L
),
Join_2 AS
(
SELECT 
	Join_1.CDCLevel AS CDCLevel,
	Join_1.HospitalDepartment AS HospitalDepartment,
	Join_1.SalesGroupingNumber AS SalesGroupingNumber,
	Join_1.NationalGroupingNumber AS NationalGroupingNumber,
	Join_1.GlobalGroupingNumber AS GlobalGroupingNumber,
	Join_1.CustomerNumbr AS CustomerNumbr,
	Join_1.IdentificationoftheCustomerinthePartnerSystem AS IdentificationoftheCustomerinthePartnerSystem,
	Join_1.DistributionCenterofCustomer AS DistributionCenterofCustomer,
	Join_1.OrderSchedulingStrategy AS OrderSchedulingStrategy,
	Join_1.ARUNGroupingStrategy AS ARUNGroupingStrategy,
	Join_1.ValueAddedServicesCustomerGroup AS ValueAddedServicesCustomerGroup,
	Join_1.VASDeterminationMode AS VASDeterminationMode,
	Join_1.CustomerVendorID AS CustomerVendorID,
	Join_1.ReleaseStrategy AS ReleaseStrategy,
	Join_1.GroupingRule AS GroupingRule,
	Join_1.CustomerGroup10 AS CustomerGroup10,
	Join_1.CustomerGroup9 AS CustomerGroup9,
	Join_1.CustomerGroup8 AS CustomerGroup8,
	Join_1.CustomerGroup7 AS CustomerGroup7,
	Join_1.CustomerGroup6 AS CustomerGroup6,
	Join_1.IndicatorForEmptiesUpdate AS IndicatorForEmptiesUpdate,
	Join_1.DepositOnEmpties AS DepositOnEmpties,
	Join_1.IndexStructureActiveforSubsequentSettlementinAB AS IndexStructureActiveforSubsequentSettlementinAB,
	Join_1.TimeframeforConfirmationofPOD AS TimeframeforConfirmationofPOD,
	Join_1.RelevantForPODProcessing AS RelevantForPODProcessing,
	Join_1.CustomerProcedureForProductProposal AS CustomerProcedureForProductProposal,
	Join_1.UnderdeliveryToleranceLimit AS UnderdeliveryToleranceLimit,
	Join_1.UnlimitedOverdeliveryAllowed AS UnlimitedOverdeliveryAllowed,
	Join_1.OverdeliveryToleranceLimit AS OverdeliveryToleranceLimit,
	Join_1.SwitchOffRounding AS SwitchOffRounding,
	Join_1.SalesBlockForCustomerSalesArea AS SalesBlockForCustomerSalesArea,
	Join_1.CreditControlArea AS CreditControlArea,
	Join_1.RelevantForPriceDeterminationID AS RelevantForPriceDeterminationID,
	Join_1.ExchangeRateType AS ExchangeRateType,
	Join_1.Startofvalidityperfortherebateindexforthecustomer AS Startofvalidityperfortherebateindexforthecustomer,
	Join_1.IndicatorCustomerIsRebateRelevant AS IndicatorCustomerIsRebateRelevant,
	Join_1.CustomerGroup5 AS CustomerGroup5,
	Join_1.CustomerGroup4 AS CustomerGroup4,
	Join_1.CustomerGroup3 AS CustomerGroup3,
	Join_1.CustomerGroup2 AS CustomerGroup2,
	Join_1.CustomerGroup1 AS CustomerGroup1,
	Join_1.DeliveringPlantOwnorExternal AS DeliveringPlantOwnorExternal,
	Join_1.TermsOfPaymentKey AS TermsOfPaymentKey,
	Join_1.AccountAssignmentGroupforCustomer AS AccountAssignmentGroupforCustomer,
	Join_1.Currency AS Currency,
	Join_1.InvoiceListSchedulecalendarIdentification AS InvoiceListSchedulecalendarIdentification,
	Join_1.ManualInvoiceMaintenance AS ManualInvoiceMaintenance,
	Join_1.Billingblockforcustomersalesanddistribution AS Billingblockforcustomersalesanddistribution,
	Join_1.ShippingConditions AS ShippingConditions,
	Join_1.DeliveryPriority AS DeliveryPriority,
	Join_1.OrderCombinationIndicator AS OrderCombinationIndicator,
	Join_1.PartialDeliveryAtItemLevel AS PartialDeliveryAtItemLevel,
	Join_1.MaximumNumberOfPartialDeliveriesAllowedPerItem AS MaximumNumberOfPartialDeliveriesAllowedPerItem,
	Join_1.CompletedDeliveryDefinedForEachSalesOrder AS CompletedDeliveryDefinedForEachSalesOrder,
	Join_1.CustomerDeliveryBlockSalesArea AS CustomerDeliveryBlockSalesArea,
	Join_1.IncotermsPart2 AS IncotermsPart2,
	Join_1.IncotermsPart1 AS IncotermsPart1,
	Join_1.OrderProbabilityOfTheItem AS OrderProbabilityOfTheItem,
	Join_1.PriceListType AS PriceListType,
	Join_1.PriceGroupCustomer AS PriceGroupCustomer,
	Join_1.SalesDistrict AS SalesDistrict,
	Join_1.PricingProcedureAssignedToThisCustomer AS PricingProcedureAssignedToThisCustomer,
	Join_1.CustomerOrderBlockSalesArea AS CustomerOrderBlockSalesArea,
	Join_1.CustomerStatisticsGroup AS CustomerStatisticsGroup,
	Join_1.DeletionFlagForCustomerSalesLevel AS DeletionFlagForCustomerSalesLevel,
	Join_1.DateonWhichRecordWasCreated AS DateonWhichRecordWasCreated,
	Join_1.NameofPersonWhoCreatedtheObject AS NameofPersonWhoCreatedtheObject,
	Join_1.Division AS Division,
	Join_1.DistributionChannel AS DistributionChannel,
	Join_1.SalesOrganization AS SalesOrganization,
	Join_1.CustomerNumber AS CustomerNumber,
	Join_1.Client AS Client,
	Join_1.HospitalDepartmentText AS HospitalDepartmentText, 
	Projection_3.DDTEXT AS CDCLevelText
FROM 
Join_1
LEFT OUTER JOIN 
Projection_3
ON Join_1.CDCLevel = Projection_3.DOMVALUE_L
)
SELECT 
	SalesGroupingNumber,
	NationalGroupingNumber,
	GlobalGroupingNumber,
	CustomerNumbr,
	IndicatorForEmptiesUpdate,
	DepositOnEmpties,
	IndexStructureActiveforSubsequentSettlementinAB,
	RelevantForPODProcessing,
	CustomerProcedureForProductProposal,
	UnderdeliveryToleranceLimit,
	SwitchOffRounding,
	SalesBlockForCustomerSalesArea,
	CreditControlArea,
	RelevantForPriceDeterminationID,
	ExchangeRateType,
	Startofvalidityperfortherebateindexforthecustomer,
	IndicatorCustomerIsRebateRelevant,
	CustomerGroup5,
	CustomerGroup4,
	CustomerGroup3,
	CustomerGroup2,
	CustomerGroup1,
	DeliveringPlantOwnorExternal,
	TermsOfPaymentKey,
	AccountAssignmentGroupforCustomer,
	Currency,
	InvoiceListSchedulecalendarIdentification,
	ManualInvoiceMaintenance,
	Billingblockforcustomersalesanddistribution,
	ShippingConditions,
	DeliveryPriority,
	OrderCombinationIndicator,
	PartialDeliveryAtItemLevel,
	MaximumNumberOfPartialDeliveriesAllowedPerItem,
	CompletedDeliveryDefinedForEachSalesOrder,
	CustomerDeliveryBlockSalesArea,
	IncotermsPart2,
	IncotermsPart1,
	OrderProbabilityOfTheItem,
	PriceListType,
	PriceGroupCustomer,
	SalesDistrict,
	PricingProcedureAssignedToThisCustomer,
	CustomerOrderBlockSalesArea,
	CustomerStatisticsGroup,
	DeletionFlagForCustomerSalesLevel,
	DateonWhichRecordWasCreated,
	NameofPersonWhoCreatedtheObject,
	Division,
	DistributionChannel,
	SalesOrganization,
	CustomerNumber,
	Client,
	HospitalDepartment,
	HospitalDepartmentText,
	CDCLevel,
	CDCLevelText
FROM Join_2 
	