WITH source AS (
	SELECT * FROM {{ source('SCM','ABC') }}
),
renamed AS (
	SELECT
		PROCEDURE_NAME,
		LAST_EXECUTION,
		LAST_EXECUTION_DATE,
		LAST_EXECUTION_TIME,
		INSERT_COUNT,
		UPDATE_COUNT,
		DELETE_COUNT
	FROM source
)
SELECT * FROM renamed